### ISSUE TITLE
Dynamic & Adjustable alignment of snap point

### ISSUE THREAD

**Issue by MartiSilvio** [polarby/snappy_list_view#1]
Hi, is there a way the left and right padding can be removed?

**Comment by polarby** [comment]
Could you please post your Configuration? I suspect you have used the `example.dart`, where I added a `Card()`widget. This widget naturally has some padding, causing each element to be slightly apart from another.

**Comment by MartiSilvio** [comment]
I am referring to the start and end padding. Not the padding between items.

**Comment by MartiSilvio** [comment]
![Screenshot_1666700500](https://user-images.githubusercontent.com/77878842/197771790-43ee3604-bffa-4c5a-9046-267829f11ff9.png)

**Comment by polarby** [comment]
Got you! Thanks for the clarification. 
For now, this is not possible, each item's intended to snap to the center when `itemSnapping: true` (therefore first and last items have to have this padding). I will add it to my list for users who just want to use a simple scroll and will make a first release by tomorrow!

**Comment by MartiSilvio** [comment]
Thank you, I have itemSnapping set to true and would like this behavior without turning off snapping.

**Comment by polarby** [comment]
A quick fix till tomorrow (which is quite bad for now) is that you could use the property `centerOffset` to move the center to the beginning, removing the side padding.

**Comment by polarby** [comment]
Where do you **expect the snap to happen after scrolling past the first few items**? Do you want to have the snap point at the position of the center of the first element for all other elements, or should the snap point 'move' toward the middle of the viewport afterward again? 

My plan now was to provide you with a `double snapAlignment` parameter to set the snap point to the start of the viewport (set it to 0 - for all children). And an additional  `bool snapAlignmentPadding` parameter to add/remove initial padding to the center trailing and leading to the snap point -> by setting this to false (only) border elements might not experience any snap effect at all in case items are too small (as the snap point is unreachable through scrolling for them).

Please take the time to review the feature proposal, so the widget can meet your needs.

**Comment by MartiSilvio** [comment]
have you ever tried Airbnb's app "Explore" page tab bar? If not, please do. that would be the optimal behavior. 
I think after scrolling a few items the snap point should progressively move to the center. As the list gets more and more exhausted I believe it should move towards the end.

**Comment by polarby** [comment]
I am gonna create a class for that so multiple snap point behaviors can be applied (also dynamic such as air BnB). Thanks for the input! This might need a few more days though...
I am still going to implement this as it is an important feature, but please check if a TabbarView widget might be more suitable for you.

**Comment by polarby** [comment]
With version 3b884e0396ffc9ef2145599f83d07dcc767e6202  you can now use `snapAlignment` and `snapOnItemAlignment` to control your requested behavior.
```dart
SnappyListView(
              snapAlignment: SnapAlignment.moveAcross(),
              snapOnItemAlignment: SnapAlignment.moveAcross(),
```
Note that if you want to add some sort of Scrollbar, I also added the parameter `onPageChange` which gives you both size and page instead of just the page when you would listen to the controller. From there on you could build & calculate the position of the scroll bar.

Feel free to add your own snap alignment behavior to it.

**Comment by MartiSilvio** [comment]
Great, thanks!
